# Generated by Django 2.0.5 on 2018-05-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='number_of_mines',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='grid',
            name='status',
            field=models.CharField(choices=[('playing', 'Playing'), ('game_over', 'Game Over')], default='playing', max_length=20),
        ),
        migrations.AlterField(
            model_name='square',
            name='explored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='square',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
